### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by reallinfo** [go-courier/courier#1]
I contribute to open source software by designing logos. If you want it, i desgined a logo for courier. What do you think? Also, Do you have a logo idea?

**Comment by morlay** [comment]
@reallinfo 
That would be awesome. Thank you so much.

These projects are named `courier` that means do something focus on  **automatic transforming and transmitting data**.
And all codes writing in go language, so I draw a bag on a [gopher](https://github.com/keygx/Go-gopher-Vector)
![image](https://user-images.githubusercontent.com/1667873/41957833-d236f960-7a1a-11e8-9531-2469721aa63d.png)

Maybe you have better idea.
Just do it with your wonderful creativity.

**Comment by reallinfo** [comment]
I wanted to design something minimalist for a logo. Also, especially if you have something you want, I can design it.

![1](https://user-images.githubusercontent.com/36298335/41965700-d82bf376-7a05-11e8-8541-8f922ed6b65b.jpg)

**Comment by morlay** [comment]
@reallinfo Thanks. 
We could let gopher go. And focus on the feature of the project.
```
data in -> one or more operators to process -> output results
```
Like this ? 😆 
![image](https://user-images.githubusercontent.com/1667873/42005348-7ec8595e-7aa6-11e8-856c-c451fe7129fe.png)
